### ISSUE TITLE
Crash when clicking Config in Mod menu on Forge 1.20.1 version

### ISSUE THREAD

**Issue by minhty-fresh** [IMB11/Fog#45]
Hi, I've noticed a crash that occurs on the Forge 1.20.1 version that occurs whenever I go to the in game Mod menu for Fog and click Config.
This occurs on a fresh install of Minecraft 1.20.1 on Forge 47.3.11 with just these mods installed
Fog 1.5.2+1.20.1-forge
MRU 1.0.3+1.20.1-forge
YACL 3.6.0+1.20.1-forge

Here's the crashlog: 
[latest.log](https://github.com/user-attachments/files/17470831/latest.log)

**Comment by Shragdhar** [comment]
Same. I'm on 1.20.1 and it crashed for me too.

**Comment by Steveplays28** [comment]
I'm going to try updating the YACL version in the JAR.

**Comment by Steveplays28** [comment]
Fixed in [`v1.5.3`](https://github.com/IMB11/Fog/releases/latest), I updated YACL to `v3.6.2`.

**Comment by Shragdhar** [comment]
@Steveplays28 I tried opening the config after updating to v1.5.3 and YACL at v3.6.2 but it still crashed. I have attached the crash report below. Also is the mod incompatible with Oculus? Although I'm not using it, it's still installed.

[crash-2024-12-26_18.12.21-client.txt](https://github.com/user-attachments/files/18252796/crash-2024-12-26_18.12.21-client.txt)

**Comment by IMB11** [comment]
This is due to an issue with how YACL was built for 1.20.1, we've dropped support for 1.20.1 due to a multitude of issues like this one. Please consider updating to 1.21 where possible.
You can still edit Fog's configuration via the JSON file.

**Comment by Shragdhar** [comment]
Unfortunately I have a custom modpack and not all mods are available for 1.21 yet. I'll have to edit the configuration file directly. Thanks!
